# Generated by Django 3.2.9 on 2021-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='asda',
            field=models.CharField(default='Adf', max_length=100, verbose_name='asd'),
        ),
    ]
